
project_id = "saglzspuqdbeopuxlktf"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public"]
max_rows = 1000

[functions.analyze-documents]
verify_jwt = false

[functions.chat-with-documents]
verify_jwt = false

[functions.extract-document-text]
verify_jwt = false

[db]
port = 54322

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_parameter_status = "off"

[realtime]
enabled = true
ip_version = "ipv4"

[studio]
enabled = true
port = 54323
