// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://saglzspuqdbeopuxlktf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNhZ2x6c3B1cWRiZW9wdXhsa3RmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjQ2MDMsImV4cCI6MjA2NTUwMDYwM30.uGD6K72bz3jQws5CWMPoY5SlIEmILoUMvjx9nVhgEPs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);